web/router.ex
defmodule Yorent.Router do
  use Yorent.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Yorent do
    pipe_through :browser # Use the default browser stack

    get       "/",          PageController, :index
    resources "/cities",    CityController do
      resources "/houses",    CityHouseController, only: [:index]
      resources "/landlords", CityLandlordController, only: [:index]
    end
    resources "/landlords", LandlordController do
      resources "/houses",    LandlordHouseController, only: [:index]
    end
    resources "/houses",    HouseController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Yorent do
  #   pipe_through :api
  # end
end

web/controllers/city_landlord_controller.ex
defmodule Yorent.CityLandlordController do
  use Yorent.Web, :controller

  alias Yorent.Landlord
  alias Yorent.House
  alias Yorent.City
  import Ecto.Query

  plug :scrub_params, "landlord" when action in [:create, :update]

  def index(conn, %{"city_id" => city_id}) do
    # Get landlords, preload city for name
    city = Repo.get!(City, city_id)
    landlords = Repo.all(Landlord |> where([l], l.city_id == ^city_id))
    # Get a map of landlord_id to number of houses
    num_houses = (Repo.all from l in Landlord, left_join: h in assoc(l, :houses), select: {l.id, count(h.id)}, group_by: l.id)
                  |> Enum.into(%{})
    # Merge num_houses into Landlord struct (creating a new map that looks like Landlord)
    landlords = Enum.map(landlords, fn(l) -> Map.merge(l, %{"num_houses": num_houses[l.id]}) end)

    render(conn, "index.html", landlords: landlords, city: city)
  end

  def new(conn, _params) do
    changeset = Landlord.changeset(%Landlord{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"landlord" => landlord_params}) do
    changeset = Landlord.changeset(%Landlord{}, landlord_params)

    case Repo.insert(changeset) do
      {:ok, _landlord} ->
        conn
        |> put_flash(:info, "Landlord created successfully.")
        |> redirect(to: landlord_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"city_id" => city_id, "id" => id}) do
    city = Repo.get!(City, city_id)
    landlord = Repo.get!(Landlord, id) |> Repo.preload(:houses) |> Repo.preload(:city)
    # num_houses = House |> where([h], h.landlord_id == ^id) |> select([h], count(h.id)) |> Repo.one!
    # IO.inspect num_houses
    render(conn, "show.html", landlord: landlord)
  end

  def edit(conn, %{"id" => id}) do
    landlord = Repo.get!(Landlord, id)
    changeset = Landlord.changeset(landlord)
    render(conn, "edit.html", landlord: landlord, changeset: changeset)
  end

  def update(conn, %{"id" => id, "landlord" => landlord_params}) do
    landlord = Repo.get!(Landlord, id)
    changeset = Landlord.changeset(landlord, landlord_params)

    case Repo.update(changeset) do
      {:ok, landlord} ->
        conn
        |> put_flash(:info, "Landlord updated successfully.")
        |> redirect(to: landlord_path(conn, :show, landlord))
      {:error, changeset} ->
        render(conn, "edit.html", landlord: landlord, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    landlord = Repo.get!(Landlord, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(landlord)

    conn
    |> put_flash(:info, "Landlord deleted successfully.")
    |> redirect(to: landlord_path(conn, :index))
  end
end

web/views/city_landlord_view.ex
defmodule Yorent.CityLandlordView do
  use Yorent.Web, :view
end

web/templates/city_landlord/edit.html.eex
<h2>Edit landlord</h2>

<%= render "form.html", changeset: @changeset,
                        action: landlord_path(@conn, :update, @landlord) %>

<%= link "Back", to: landlord_path(@conn, :index) %>

web/templates/city_landlord/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, "Name", class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :type, "Type", class: "control-label" %>
    <%= text_input f, :type, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :average_rating, "Average rating", class: "control-label" %>
    <%= number_input f, :average_rating, step: "any", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :website, "Website", class: "control-label" %>
    <%= text_input f, :website, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/city_landlord/index.html.eex
<h2>All landlords in <%= @city.name %></h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Average rating</th>
      <th>Number of properties</th>
      <th>Website</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for landlord <- @landlords do %>
    <tr>
      <td><%= link landlord.name, to: landlord_path(@conn, :show, landlord) %></td>
      <td><%= landlord.type %></td>
      <td><%= landlord.average_rating %></td>
      <td><%= link "#{landlord.num_houses}", to: landlord_landlord_house_path(@conn, :index, landlord) %></td>
      <td><%= link landlord.website, to: landlord.website %></td>

      <td class="text-right">
        <!-- <%= link "Show", to: landlord_path(@conn, :show, landlord), class: "btn btn-default btn-xs" %> -->
        <%= link "Edit", to: landlord_path(@conn, :edit, landlord), class: "btn btn-default btn-xs" %>
        <!-- <%= link "Delete", to: landlord_path(@conn, :delete, landlord), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %> -->
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New landlord", to: landlord_path(@conn, :new) %>

web/templates/city_landlord/new.html.eex
<h2>New landlord</h2>

<%= render "form.html", changeset: @changeset,
                        action: landlord_path(@conn, :create) %>

<%= link "Back", to: landlord_path(@conn, :index) %>

web/templates/city_landlord/show.html.eex
<h2>Show landlord</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @landlord.name %>
  </li>

  <li>
    <strong>Type:</strong>
    <%= @landlord.type %>
  </li>

  <li>
    <strong>Average rating:</strong>
    <%= @landlord.average_rating %>
  </li>

  <li>
    <strong>Website:</strong>
    <%= @landlord.website %>
  </li>

  <li>
    <strong>City:</strong>
    <%= @landlord.city.name %>
  </li>

  <ul>
    <%= for house <- @landlord.houses do %>
    <li><%= link house.name, to: house_path(@conn, :show, house) %></li>
    <% end %>

  </ul>


</ul>

<%= link "Edit", to: landlord_path(@conn, :edit, @landlord) %>
<%= link "Back", to: landlord_path(@conn, :index) %>