web/router.ex
defmodule Yorent.Router do
  use Yorent.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Yorent do
    pipe_through :browser # Use the default browser stack

    get       "/",          PageController, :index
    resources "/cities",    CityController do
      resources "/houses",    CityHouseController, only: [:index]
      resources "/landlords", CityLandlordController, only: [:index]
    end
    resources "/landlords", LandlordController do
      resources "/houses",    LandlordHouseController, only: [:index]
    end
    resources "/houses",    HouseController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Yorent do
  #   pipe_through :api
  # end
end

web/models/city.ex
defmodule Yorent.City do
  use Yorent.Web, :model

  schema "cities" do
    field :name, :string
    has_many :houses, Yorent.House
    has_many :landlords, Yorent.Landlord
    timestamps
  end

  @required_fields ~w(name)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/city_controller.ex
defmodule Yorent.CityController do
  use Yorent.Web, :controller

  alias Yorent.City
  alias Yorent.Landlord
  alias Yorent.House
  plug :scrub_params, "city" when action in [:create, :update]

  def index(conn, _params) do
    cities = Repo.all(City)

    num_houses = (Repo.all from c in City, left_join: h in assoc(c, :houses), select: {c.id, count(h.id)}, group_by: c.id)
                  |> Enum.into(%{})
    cities = Enum.map(cities, fn(c) -> Map.merge(c, %{"num_houses": num_houses[c.id]}) end)

    num_landlords = (Repo.all from c in City, left_join: l in assoc(c, :landlords), select: {c.id, count(l.id)}, group_by: c.id)
                  |> Enum.into(%{})
    cities = Enum.map(cities, fn(c) -> Map.merge(c, %{"num_landlords": num_landlords[c.id]}) end)

    render(conn, "index.html", cities: cities)
  end

  def new(conn, _params) do
    changeset = City.changeset(%City{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"city" => city_params}) do
    changeset = City.changeset(%City{}, city_params)

    case Repo.insert(changeset) do
      {:ok, _city} ->
        conn
        |> put_flash(:info, "City created successfully.")
        |> redirect(to: city_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    city = Repo.get!(City, id)
    num_landlords = Repo.all(from l in Landlord, where: l.city_id == ^id, select: count(l.id))
    num_houses = Repo.all(from h in House, where: h.city_id == ^id, select: count(h.id))
    # Returns char array, need to convert to string/int instead of byte
    [num_houses | _] = num_houses
    [num_landlords | _] = num_landlords
    render(conn, "show.html", city: city,
                              num_landlords: num_landlords,
                              num_houses: num_houses)
  end

  def edit(conn, %{"id" => id}) do
    city = Repo.get!(City, id)
    changeset = City.changeset(city)
    render(conn, "edit.html", city: city, changeset: changeset)
  end

  def update(conn, %{"id" => id, "city" => city_params}) do
    city = Repo.get!(City, id)
    changeset = City.changeset(city, city_params)

    case Repo.update(changeset) do
      {:ok, city} ->
        conn
        |> put_flash(:info, "City updated successfully.")
        |> redirect(to: city_path(conn, :show, city))
      {:error, changeset} ->
        render(conn, "edit.html", city: city, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    city = Repo.get!(City, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(city)

    conn
    |> put_flash(:info, "City deleted successfully.")
    |> redirect(to: city_path(conn, :index))
  end
end

web/views/city_view.ex
defmodule Yorent.CityView do
  use Yorent.Web, :view
end

web/templates/city/edit.html.eex
<h2>Edit city</h2>

<%= render "form.html", changeset: @changeset,
                        action: city_path(@conn, :update, @city) %>

<%= link "Back", to: city_path(@conn, :index) %>

web/templates/city/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, "Name", class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/city/index.html.eex
<h2>Choose your city</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Landlords</th>
      <th>Number of Houses</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for city <- @cities do %>
    <tr>
      <td><%= link city.name, to: city_path(@conn, :show, city) %></td>

      <td><%= city.num_landlords %></td>
      <%= link city.num_houses, to: city_city_landlord_path(@conn, :index, city) %>
      <td><%= city.num_houses %></td>

    </tr>
<% end %>
  </tbody>
</table>

<%= link "New city", to: city_path(@conn, :new) %>

web/templates/city/new.html.eex
<h2>New city</h2>

<%= render "form.html", changeset: @changeset,
                        action: city_path(@conn, :create) %>

<%= link "Back", to: city_path(@conn, :index) %>

web/templates/city/show.html.eex
<h2>Welcome to <%=@city.name%></h2>
<h3>Let's find you a nice place to live</h3>

<ul>

  <li>
    <h4><%= link "Choose by Letting Agent", to: city_city_landlord_path(@conn, :index, @city) %></h4>
    <p><%=@city.name%> has <%= @num_landlords %> agents.</p>
    <p>Pick a landlord according to their satisfaction rating, and we'll show your what houses they have available</p>
  </li>

  <li>
    <h4>Pick an area</h4>
    <p>Need to live near the university or the station?</p>
    <p>We'll find the best houses in the ideal location</p>
  </li>

  <li>
    <h4><%= link "Show all houses in #{@city.name}", to: city_city_house_path(@conn, :index, @city) %></h4>
    <p>A mega list of all <%=@num_houses%>  houses in York</p>
    <p>Filter and sort all the houses until you find the perfect pad</p>
  </li>

    <!-- <li>
      <strong>Name:</strong>
      <%= @city.name %>
    </li>

    <li>
      <strong>Landlords:</strong>
      <%= @num_landlords %>
      <%= link "Show all landlords in #{@city.name}", to: city_city_landlord_path(@conn, :index, @city) %>

    </li>

    <li>
      <strong>Houses:</strong>
      <%= @num_houses %>
      <%= link "Show all houses in #{@city.name}", to: city_city_house_path(@conn, :index, @city) %>

    </li> -->

</ul>

<%= link "Edit", to: city_path(@conn, :edit, @city) %>
<%= link "Back", to: city_path(@conn, :index) %>