web/router.ex
defmodule Yorent.Router do
  use Yorent.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Yorent do
    pipe_through :browser # Use the default browser stack

    get       "/",          PageController, :index
    resources "/cities",    CityController do
      resources "/houses",    CityHouseController, only: [:index]
      resources "/landlords", CityLandlordController, only: [:index]
    end
    resources "/landlords", LandlordController do
      resources "/houses",    LandlordHouseController, only: [:index]
    end
    resources "/houses",    HouseController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Yorent do
  #   pipe_through :api
  # end
end

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Welcome to YoRent!</h2>
  <p class="lead">Helping people find great places to live<br />and other interesting tagline things.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <%= link "Cities", to: city_path(@conn, :index)%>
      </li>
      <li>
        <%= link "Landlords", to: landlord_path(@conn, :index)%>
      </li>
      <li>
        <%= link "Houses", to: house_path(@conn, :index)%>
      </li>
    </ul>
  </div>
</div>